[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NEXT_PUBLIC_BASE_URL="https://synth-blog.netlify.app/"
  BASE_URL="https://synth-blog.netlify.app/"

[[plugins]]
  package = "@netlify/plugin-nextjs"