name: Synth blog platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: 
        npm install
        npm install pnpm 
        npm install @netlify/plugin-nextjs@^5.12.0
        pnpm install
        npm ci

    - name: Build Next.js app
      run: npm run build

    - name: Deploy to netlify
      uses: nwtgck/actions-netlify@v2
      with:
        publish-dir: ./.next
        production-branch: master
        github-token: ${{secrets.GITHUB_TOKEN}}
        deploy-message: "Deploy from github actions"
        netlify-config-path: netlify.toml
        enable-pull-request-comment: true

